name: Build and draft release

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  DOCKER_USERNAME: laurihuotari

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ env.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define image meta
        id: meta
        uses: docker/metadata-action@v3
        with:
            images: ${{ env.DOCKER_USERNAME }}/lxc-proxy
            tags: |
              type=raw,value=sha-${{ github.sha }}
            flavor: |
              latest=true

      - name: Build image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: Dockerfile
            no-cache: false
            push: false
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              VERSION=sha-${{ github.sha }}
